version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "/usr/bin/mysql",
          "--user=root",
          "--password=admin",
          "--execute",
          "SHOW DATABASES;"
        ]
      interval: 2s
      timeout: 30s
      retries: 60
  api:
    image: python:3.10-slim-buster
    restart: always
    environment:
      - FLASK_APP=app.py
      - BLOG_APP_ENV=dev
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    command: >
      bash -c "apt-get update && apt-get install python3-dev default-libmysqlclient-dev pkg-config build-essential -y && pip3 install -r requirements.txt && flask db upgrade && python3 -m flask run --host=0.0.0.0"
    working_dir: /app
    volumes:
      - ./:/app:ro
    depends_on:
      db:
        condition: service_healthy
volumes:
  db:
    driver: local
